### ISSUE TITLE
Vods?

### ISSUE THREAD

**Issue by AzureDem** [tommyxchow/frosty#208] opened 2022-11-04 06:33 UTC
I’m not sure how hard it’d be, but I’d really like to be able to watch past vods on the phone with chat too. This would make the app perfect.

**Comment by tommyxchow** [comment] 2023-01-17 01:34
Unfortunately, as with many missing features, Twitch does not support VOD chats in their current API (more details in #134). Sorry about this.

Duplicate of #134

**Closed by tommyxchow** 2023-01-17 01:34 UTC
Labels: feature request
