### ISSUE TITLE
A way to see streamers page and watch VOD of past streams 

### ISSUE THREAD

**Issue by TemporaryCrown** [tommyxchow/frosty#207] opened 2022-11-02 20:09 UTC
A way to view a streamers page and watch there old VODS of past streams or videos with chat

**Comment by tommyxchow** [comment] 2023-01-17 01:20
Unfortunately, as with many missing features, Twitch does not support VOD chats in their current API (more details in #134). Sorry about this.

Duplicate of #134.

**Closed by tommyxchow** 2023-01-17 01:20 UTC
Labels: feature request
