### ISSUE TITLE
I can't log into the app. After giving it permission to my twitch account it just goes back to streams and I'm not logged. I'm on Android 10

### ISSUE THREAD

**Issue by Szado33** [tommyxchow/frosty#147] opened 2022-06-15 19:27 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 13, Pixel 6]
 - OS: [e.g. iOS 15, Android 12]
 - App Version: [check in Settings -> Other -> About Frosty. e.g. v1.4.1 (22)]

**Additional context**

**Comment by tommyxchow** [comment] 2022-06-24 05:25
I'm streamlining the login method that hopefully will fix this odd behavior.

Closing this, a duplicate of #139.

**Closed by tommyxchow** 2022-06-24 05:25 UTC
Labels: bug
