### ISSUE TITLE
Login issue 

### ISSUE THREAD

**Issue by Giggles22031** [tommyxchow/frosty#139] opened 2022-06-04 07:31 UTC
**Describe the bug**
Unable to login 

**To Reproduce**
1. Go to settings
2. Click on Account
3. Click on Log In
4. Click on Connect with Twitch
5. Click on Authorize 

**Expected behavior**
It would Log In me in instead, it just takes me back to the settings page

**Screenshots**
https://imgur.com/a/ZR9CgVR

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15.6
 - App Version: 1.4.1

**Comment by tommyxchow** [comment] 2022-06-04 23:50
I can't seem to reproduce it on my end. If you haven't tried it already, restarting the app should fix it. If not, try reinstalling the app.

**Comment by Giggles22031** [comment] 2022-06-05 02:53
restarting the app has 2 outcomes it'll either freeze on the loading screen or the account section will have "Failed to Connect" with a try again button

**Comment by tommyxchow** [comment] 2022-06-05 05:42
I just tried the public beta for iOS 15.6 and sadly still can't reproduce it. It sounds like the login details (token) from Twitch somehow got corrupted when connecting with Twitch. Reinstalling the app will clear all the tokens and reset everything to square one. Without a consistent way for me to reproduce this, it'll be difficult to get to the bottom of this bug. Sorry for the inconvenience.

**Comment by tommyxchow** [comment] 2022-07-27 22:56
I've recently overhauled the login method in v2.0.0. Hopefully it will have resolved it for you.

I'm reluctantly closing this issue as I've yet to figure out a way to reproduce the login not working.

**Closed by tommyxchow** 2022-07-27 22:56 UTC
Labels: bug
