### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by notNSANE** [tommyxchow/frosty#111] opened 2022-04-19 17:11 UTC
I tried several times, I authorized the app but it never works.

Also, no idea how to login using the token.

**Comment by tommyxchow** [comment] 2022-04-19 23:10
Hello, if you could provide the following information I may be able to take a closer look at what's preventing the authorization from working:
- Android or iOS version
- Device name
- App version (you can check in Settings -> Other -> About Frosty)

Also, if possible, could you provide a video of the login process failing? It would help me pinpoint which part is causing an error.

**Comment by notNSANE** [comment] 2022-04-20 01:11
Android 11
Samsung A22
Version 1.2.2 (20)

I cannot send a video, but after clicking on the "authorize" button after logging via the "connect with twitch" option; I get redirected to a blank page that says "redirecting you automatically..." etc.

And nothing more happens, it just stays there forever and I'm still not logged it.

**Comment by tommyxchow** [comment] 2022-04-20 02:57
> Android 11 Samsung A22 Version 1.2.2 (20)
> 
> I cannot send a video, but after clicking on the "authorize" button after logging via the "connect with twitch" option; I get redirected to a blank page that says "redirecting you automatically..." etc.
> 
> And nothing more happens, it just stays there forever and I'm still not logged in.

Also, which browser are you using? I've somewhat managed to reproduce the bug with other browsers, but the login still works in the end.

A possible workaround, for now, is to simply go back to the app after reaching the "Redirecting you automatically..." page. It should log you in automatically. If that doesn't work, try tapping the "click here" on that page instead and then go back to the app.

Nonetheless, I'll work on making the login use the in-app browser rather than going to an external browser since there are definitely some compatibility issues with some of the hundreds of browsers on Android. Since the current implementation uses [Chrome Custom Tabs](https://developer.chrome.com/docs/android/custom-tabs/), using a non-Chrome browser causes some unintended behavior.

**Comment by notNSANE** [comment] 2022-04-20 03:02
Vivaldi, but in this case I was using the in-app browser. Just in case, I'll do a data reset and try again both ways.

**Comment by notNSANE** [comment] 2022-04-20 06:46
No luck, still can't login.

**Comment by tommyxchow** [comment] 2022-05-03 05:05
> update, I switched to Samsung Internet for this and I could login at the first try

Hey, first of all very sorry for the late reply, I've been busy with other things lately. 

Happy to hear that the login is working with a different browser. In conclusion, this _seems_ like a problem with certain browsers rather than the app, so I'll be closing the issue.

**Closed by tommyxchow** 2022-05-03 05:05 UTC
Labels: bug
